#!/bin/sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 0
sleep 2
xrandr --output DP-0.1 --mode 1920x1080 --pos 0x360 --rotate normal --output DP-0.2 --primary --mode 2560x1440 --pos 4864x0 --rotate normal --output DP-0.3 --mode 1024x768 --pos 1920x672 --rotate normal --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output eDP-1-1 --mode 1920x1080 --pos 2944x360 --rotate normal
nvidia-settings --assign "CurrentMetaMode=DP-0.1: nvidia-auto-select +0+360 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-0.2: nvidia-auto-select +4864+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-0.3: nvidia-auto-select +1920+672 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

# restart stuff
sleep 2
killall conky
bash ~/.dotfiles/xinit/util/restore-desktop
xmonad --restart
bash ~/.conky/conky-startup.sh
qtile-cmd -o cmd -f restart
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1

# set metamodes
