#!/bin/sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 0
sleep 2
xrandr --output DP-0.1 --off --output DP-0.2 --off --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
sleep 2
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1
sleep 2
killall conky
bash ~/.dotfiles/xinit/util/restore-desktop
xmonad --restart
qtile-cmd -o cmd -f restart
bash ~/.conky/conky-startup.sh
