#!/bin/sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 0
xrandr --output DP-1.1 --off --output DP-1.2 --off --output DP-1.3 --off --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal

# restart stuff
sleep 2
killall conky
bash ~/.dotfiles/xinit/util/restore-desktop
xmonad --restart
qtile-cmd -o cmd -f restart
bash ~/.conky/conky-startup.sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1

# set metamodes
