#!/bin/sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 0
sleep 2
xrandr --output DP-1.1 --off --output DP-1.2 --primary --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-1.3 --off --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output eDP-1-1 --mode 1920x1080 --pos 0x360 --rotate normal
sleep 2
nvidia-settings --assign "CurrentMetaMode=nvidia-auto-select +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

# restart stuff
sleep 2
killall conky
bash ~/.dotfiles/xinit/util/restore-desktop
xmonad --restart
qtile-cmd -o cmd -f restart
bash ~/.conky/conky-startup.sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1

# set metamodes
