#!/bin/sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 0
xrandr --output DP-1.2 --primary --mode 3840x2160 --pos 1920x0 --rotate normal --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output DP-1.3 --mode 1280x1024 --pos 5760x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal
nvidia-settings --assign "CurrentMetaMode=DP-1.2: nvidia-auto-select +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-1.3: 1280x1024 +5760+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

# restart stuff
sleep 2
killall conky
bash ~/.dotfiles/xinit/util/restore-desktop
xmonad --restart
qtile-cmd -o cmd -f restart
bash ~/.conky/conky-startup.sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1

# set metamodes
