#!/bin/sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 0
nvidia-settings --assign "CurrentMetaMode=DP-1.2: 2560x1440_60 +3200+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-1.3: 1280x1024_75 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

# restart stuff
sleep 2
killall conky
bash ~/.dotfiles/xinit/util/restore-desktop
xmonad --restart
qtile-cmd -o cmd -f restart
bash ~/.conky/conky-startup.sh
xrandr --output eDP-1-1 --set "PRIME Synchronization" 1

# set metamodes
