#!/bin/bash
[[ -n $LAIN_SOUNDS ]] && aplay ~/.sounds/smw_message_block.wav 2>/dev/null >/dev/null &
ROFI_CONFIG_FILE=$HOME/.config/rofi/config.rasi PATH=$PATH:$HOME/bin:$HOME/.util rofi -show run
[[ -n $LAIN_SOUNDS ]] && aplay ~/.sounds/smw_midway_gate.wav
